package lab1.mybatis.model;

public class Author {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.AUTHOR.ID
     *
     * @mbg.generated Mon Apr 28 12:23:32 EEST 2025
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.AUTHOR.FIRST_NAME
     *
     * @mbg.generated Mon Apr 28 12:23:32 EEST 2025
     */
    private String firstName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.AUTHOR.LAST_NAME
     *
     * @mbg.generated Mon Apr 28 12:23:32 EEST 2025
     */
    private String lastName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.AUTHOR.ID
     *
     * @return the value of PUBLIC.AUTHOR.ID
     *
     * @mbg.generated Mon Apr 28 12:23:32 EEST 2025
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.AUTHOR.ID
     *
     * @param id the value for PUBLIC.AUTHOR.ID
     *
     * @mbg.generated Mon Apr 28 12:23:32 EEST 2025
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.AUTHOR.FIRST_NAME
     *
     * @return the value of PUBLIC.AUTHOR.FIRST_NAME
     *
     * @mbg.generated Mon Apr 28 12:23:32 EEST 2025
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.AUTHOR.FIRST_NAME
     *
     * @param firstName the value for PUBLIC.AUTHOR.FIRST_NAME
     *
     * @mbg.generated Mon Apr 28 12:23:32 EEST 2025
     */
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.AUTHOR.LAST_NAME
     *
     * @return the value of PUBLIC.AUTHOR.LAST_NAME
     *
     * @mbg.generated Mon Apr 28 12:23:32 EEST 2025
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.AUTHOR.LAST_NAME
     *
     * @param lastName the value for PUBLIC.AUTHOR.LAST_NAME
     *
     * @mbg.generated Mon Apr 28 12:23:32 EEST 2025
     */
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
}