package lab1.mybatis.model;

public class Bookstore {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.BOOKSTORE.ID
     *
     * @mbg.generated Mon Apr 28 12:23:32 EEST 2025
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.BOOKSTORE.NAME
     *
     * @mbg.generated Mon Apr 28 12:23:32 EEST 2025
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.BOOKSTORE.ID
     *
     * @return the value of PUBLIC.BOOKSTORE.ID
     *
     * @mbg.generated Mon Apr 28 12:23:32 EEST 2025
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.BOOKSTORE.ID
     *
     * @param id the value for PUBLIC.BOOKSTORE.ID
     *
     * @mbg.generated Mon Apr 28 12:23:32 EEST 2025
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.BOOKSTORE.NAME
     *
     * @return the value of PUBLIC.BOOKSTORE.NAME
     *
     * @mbg.generated Mon Apr 28 12:23:32 EEST 2025
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.BOOKSTORE.NAME
     *
     * @param name the value for PUBLIC.BOOKSTORE.NAME
     *
     * @mbg.generated Mon Apr 28 12:23:32 EEST 2025
     */
    public void setName(String name) {
        this.name = name;
    }
}