package lab1.mybatis.model;

public class BooksBookstores {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.BOOKS_BOOKSTORES.BOOKS_ID
     *
     * @mbg.generated Mon Apr 28 12:23:32 EEST 2025
     */
    private Long booksId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.BOOKS_BOOKSTORES.STORES_ID
     *
     * @mbg.generated Mon Apr 28 12:23:32 EEST 2025
     */
    private Long storesId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.BOOKS_BOOKSTORES.BOOKS_ID
     *
     * @return the value of PUBLIC.BOOKS_BOOKSTORES.BOOKS_ID
     *
     * @mbg.generated Mon Apr 28 12:23:32 EEST 2025
     */
    public Long getBooksId() {
        return booksId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.BOOKS_BOOKSTORES.BOOKS_ID
     *
     * @param booksId the value for PUBLIC.BOOKS_BOOKSTORES.BOOKS_ID
     *
     * @mbg.generated Mon Apr 28 12:23:32 EEST 2025
     */
    public void setBooksId(Long booksId) {
        this.booksId = booksId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.BOOKS_BOOKSTORES.STORES_ID
     *
     * @return the value of PUBLIC.BOOKS_BOOKSTORES.STORES_ID
     *
     * @mbg.generated Mon Apr 28 12:23:32 EEST 2025
     */
    public Long getStoresId() {
        return storesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.BOOKS_BOOKSTORES.STORES_ID
     *
     * @param storesId the value for PUBLIC.BOOKS_BOOKSTORES.STORES_ID
     *
     * @mbg.generated Mon Apr 28 12:23:32 EEST 2025
     */
    public void setStoresId(Long storesId) {
        this.storesId = storesId;
    }
}