package lab1.mybatis.dao;

import java.util.List;

import lab1.mybatis.model.Book;
import lab1.mybatis.model.BooksBookstores;
import lab1.mybatis.model.Bookstore;
import org.mybatis.cdi.Mapper;

@Mapper
public interface BooksBookstoresMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.BOOKS_BOOKSTORES
     *
     * @mbg.generated Mon Apr 28 12:23:32 EEST 2025
     */
    int insert(BooksBookstores row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.BOOKS_BOOKSTORES
     *
     * @mbg.generated Mon Apr 28 12:23:32 EEST 2025
     */
    List<BooksBookstores> selectAll();

    List<Bookstore> selectByBookId(int bookId);

    List<Book> selectByBookstoreId(int bookstoreId);
}