package lab1.mybatis.dao;

import java.util.List;
import lab1.mybatis.model.Bookstore;
import org.mybatis.cdi.Mapper;

@Mapper
public interface BookstoreMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.BOOKSTORE
     *
     * @mbg.generated Mon Apr 28 12:23:32 EEST 2025
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.BOOKSTORE
     *
     * @mbg.generated Mon Apr 28 12:23:32 EEST 2025
     */
    int insert(Bookstore row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.BOOKSTORE
     *
     * @mbg.generated Mon Apr 28 12:23:32 EEST 2025
     */
    Bookstore selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.BOOKSTORE
     *
     * @mbg.generated Mon Apr 28 12:23:32 EEST 2025
     */
    List<Bookstore> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.BOOKSTORE
     *
     * @mbg.generated Mon Apr 28 12:23:32 EEST 2025
     */
    int updateByPrimaryKey(Bookstore row);
}